[pytest]
markers =
    smoke: Быстрая проверка
    constructor: Тесты конструктора бургеров
    modal: Тесты модальных окон
    navigation: Тесты навигации по сайту
    order_feed: Тесты ленты заказов